name: app
description: "J’agis vous accompagne à chaque étape de la transition écologique."
publish_to: 'none'
version: 0.16.9+0

environment:
  sdk: 3.7.0
  flutter: 3.29.0

dependencies:
  clock: 1.1.2
  collection: 1.19.1
  cupertino_icons: 1.0.8
  device_info_plus: 11.3.0
  dio: 5.8.0+1
  dsfr:
    path: ../packages/dsfr.dart
  equatable: 2.0.7
  firebase_core: 3.12.0
  firebase_messaging: 15.2.3
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  flutter_inset_shadow: 2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.7.6+2
  flutter_native_splash: 2.4.5
  flutter_secure_storage: 9.2.4
  flutter_widget_from_html_core: 0.16.0
  fpdart: 1.1.1
  fwfh_url_launcher: 0.16.0
  go_router: 14.8.0
  html: 0.15.5
  intl: 0.19.0 # Bloqué en 0.19.0 par flutter_localizations
  jovial_svg: 1.1.25
  matomo_tracker: 6.0.0-dev.1
  meta: 1.16.0
  mocktail_image_network: 1.2.0
  native_dio_adapter: 1.4.0
  package_info_plus: 8.2.1
  pinput: 5.0.1
  rxdart: 0.28.0
  sentry_dio: 8.13.1
  sentry_flutter: 8.13.1
  url_launcher: 6.3.1

dev_dependencies:
  bdd_widget_test: 1.8.0
  build_runner: 2.4.15
  dart_code_metrics_presets: 2.21.0
  faker: 2.2.0
  flutter_launcher_icons: 0.14.3
  flutter_test:
    sdk: flutter
  jagis_lints:
    path: ../packages/jagis_lints
  mocktail: 1.0.4
  nested: 1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

# 'dart run flutter_native_splash:create' to update
flutter_native_splash:
  color: "#EDFEE7"
  color_dark: "#EDFEE7"
  image: "assets/launcher_icons/icon-splashscreen.png"
  android_12:
    image: "assets/launcher_icons/icon-splashscreen.png"
    icon_background_color: "#EDFEE7"
    icon_background_color_dark: "#EDFEE7"
